
//var month = new Array("January","February","March","April","May","June","July","August",
//"September","October","November","December");
var Cloas_ods = {"name":"Cloas_ods","body":"  Hi,\n\n  You are receiving this communication because you are one of the users of CLOAS ODS or its downstream.\n\n  Issue –\n  There will be a delay in CLOAS ODS downstreams as there was a delay in reception of files from source. PFA notifications from source.\n                  CLOAS ODS load process has successfully completed. The downstream processes are currently running.\n  Action –\n          We will keep you posted about the progress of the same.\n  ETA    -\n  Next Update –\n          In 2 Hours.\n  Impact –\n          These applications loads might be delayed:\n          CLEAR\n          CIRCLE REPORTING\n          COCKPIT REPORTING\n          LTC EXPERIENCE\n\n  In case of any issues/concerns/questions, kindly drop an email to GNWETLRPSUPP@genworth.com.\n  ", "subject" : "Important notification ", "cc" : "akshay.ghatage@capgemini.com;kunal.amritkar@capgemini.com","to" : "akshay.ghatage@capgemini.com;kunal.amritkar@capgemini.com"};

var Cloas_ods_1 = {"name":"Cloas_ods_1","body":"  Hi,\n\n  You are receiving this communication because you are one of the users of CLOAS ODS or its downstream.\n\n  Issue –\n  There will be a delay in CLOAS ODS downstreams as there was a delay in reception of files from source. PFA notifications from source.\n                  CLOAS ODS load process has successfully completed. The downstream processes are currently running.\n  Action –\n          We will keep you posted about the progress of the same.\n  ETA    -\n  Next Update –\n          In 2 Hours.\n  Impact –\n          These applications loads might be delayed:\n          CLEAR\n          CIRCLE REPORTING\n          COCKPIT REPORTING\n          LTC EXPERIENCE\n\n  In case of any issues/concerns/questions, kindly drop an email to GNWETLRPSUPP@genworth.com.\n  ", "subject" : "Important notification ", "cc" : "akshay.ghatage@capgemini.com;kunal.amritkar@capgemini.com","to" : "akshay.ghatage@capgemini.com"};
var Cloas_ods_2 = {"name":"Cloas_ods_2","body":"  Hi,\n\n  You are receiving this communication because you are one of the users of CLOAS ODS or its downstream.\n\n  Issue –\n  There will be a delay in CLOAS ODS downstreams as there was a delay in reception of files from source. PFA notifications from source.\n                  CLOAS ODS load process has successfully completed. The downstream processes are currently running.\n  Action –\n          We will keep you posted about the progress of the same.\n  ETA    -\n  Next Update –\n          In 2 Hours.\n  Impact –\n          These applications loads might be delayed:\n          CLEAR\n          CIRCLE REPORTING\n          COCKPIT REPORTING\n          LTC EXPERIENCE\n\n  In case of any issues/concerns/questions, kindly drop an email to GNWETLRPSUPP@genworth.com.\n  ", "subject" : "Important notification ", "cc" : "akshay.ghatage@capgemini.com;kunal.amritkar@capgemini.com","to" : "akshay.ghatage@capgemini.com"};
var Cloas_ods_3 = {"name":"Cloas_ods_3","body":"  Hi,\n\n  You are receiving this communication because you are one of the users of CLOAS ODS or its downstream.\n\n  Issue –\n  There will be a delay in CLOAS ODS downstreams as there was a delay in reception of files from source. PFA notifications from source.\n                  CLOAS ODS load process has successfully completed. The downstream processes are currently running.\n  Action –\n          We will keep you posted about the progress of the same.\n  ETA    -\n  Next Update –\n          In 2 Hours.\n  Impact –\n          These applications loads might be delayed:\n          CLEAR\n          CIRCLE REPORTING\n          COCKPIT REPORTING\n          LTC EXPERIENCE\n\n  In case of any issues/concerns/questions, kindly drop an email to GNWETLRPSUPP@genworth.com.\n  ", "subject" : "Important notification ", "cc" : "akshay.ghatage@capgemini.com;kunal.amritkar@capgemini.com","to" : "akshay.ghatage@capgemini.com"};




var issueList = new Array(Cloas_ods,Cloas_ods_1,Cloas_ods_2,Cloas_ods_3);
